### ISSUE TITLE
Suitability for general replacement of simulacrum in scala-uri

### ISSUE THREAD

**Issue by easel** [typelevel/simulacrum-scalafix#37]
Apologies in advance for opening such a "User Error" issue =/

Due to what seems to be an incompatibility between simulacrum and scala.js 1.0 (https://github.com/lemonlabsuk/scala-uri/issues/152) I thought I'd give this tool a try at replacing simulacrum. So far, I've been unable to get the rules to "do" anything, although they run just fine.

Should they work outside of cats? My assumption is they should and that I've made a trivial operator error but so far I'm having trouble tracking it down. The configuration I'm using is at https://github.com/easel/scala-uri/commit/181664200a17899f22da5804e76e40576114a383 

I'd greatly appreciate any hints as to why `scalafix AddSerializable` processes the source files but doesn't actually change anything.

**Comment by travisbrown** [comment]
> Should they work outside of cats?

Yes, for sure. Whether they will or not is a completely different question, since so far I'm not sure anyone has tried to use them outside of the context of the tests here and Cats itself. :smile:

In this case I think the issue is with some assumptions about the source that are used to identify the targets for the rules. I have a quick hack fix that seems to work for that scala-uri branch, and will try to publish an 0.4.1 release later this evening or tomorrow.

**Comment by easel** [comment]
Thanks @travisbrown, that's awesome!

**Comment by easel** [comment]
I've updated to the 0.5.0 release and it works like a charm. Thanks again!
